name: Check Google Website

on:
  schedule:
    - cron: '*/0 * * * *' 
  workflow_dispatch:        

jobs:
  check-google:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar si Google responde correctamente
        run: |
          URL="https://www.google.com"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Google no responde: Codigo HTTP: $RESPONSE"
            exit 1
          else
            echo "Google Funciona: Código HTTP: $RESPONSE"
          fi
